### ISSUE TITLE
design database structure

### ISSUE THREAD

**Issue by dlpeters** [WebDevBootcamp/archiVe#10]
decide what structure will be used for the database. Will we need an actual database?

**Comment by selinaross** [comment]
I have some ideas about the database structures. Perhaps we could have two tables: 1) Books Table, 2) Shelves Table. The Books Table would receive the data from the Google Book API, then the user could drag and drop thumbnails to the Shelves Table, placing them on desired shelves. 

Rough example of tables:
https://cloud.githubusercontent.com/assets/10564028/7558237/08099550-f75d-11e4-8fe5-ac558d2178ea.PNG

Is this what others have in mind? I'm completely open to suggestions. I just wanted to get my thoughts out there.

**Comment by patrickmulcrone** [comment]
Should each record be collection name (that is populated by up to 10 IDs)? or something more granular?

**Comment by selinaross** [comment]
We will not need to create a database if we use localStorage HTML5 (data is stored locally in user's browser): 
https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#localStorage

**Comment by nw** [comment]
I think it's a great idea to prototype with local storage. Much easier to experiment with. If you nail down a data structure you can always add the complexity of a full blown db later.

**Comment by selinaross** [comment]
Thanks! Ben told us about this option last night - seems like it will be really doable.

**Comment by ysjoyce** [comment]
I plan to try some code trials today. Are you going to Boulder this afternoon?

**Comment by selinaross** [comment]
Ooh, I'm just seeing your comment now Yvonne. Sorry for not replying.

**Comment by selinaross** [comment]
Group decided to use LocalStorage HTML5 instead of creating a db.
