### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by selinaross** [WebDevBootcamp/archiVe#14]
Research draggable/droppable jQuery UI (for dragging "books" to "collections").
https://jqueryui.com/draggable/
https://jqueryui.com/droppable/

**Comment by patrickmulcrone** [comment]
Also, you can drag and drop directly in HTML, but I don't know if that is better or worse than jQuery

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop

**Comment by nw** [comment]
I would stick with the jqueryui. It will be easier to use.

**Comment by selinaross** [comment]
Sample code for draggable/droppable functionality from jqueryui.com (to modify for our purposes). Try it in jsfiddle.net

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Droppable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <style>
  #draggable { width: 100px; height: 100px; padding: 0.5em; float: left; margin: 10px 10px 10px 0; }
  #droppable { width: 150px; height: 150px; padding: 0.5em; float: left; margin: 10px; }
  </style>
  <script>
  $(function() {
    $( "#draggable" ).draggable();
    $( "#droppable" ).droppable({
      drop: function( event, ui ) {
        $( this )
          .addClass( "ui-state-highlight" )
          .find( "p" )
            .html( "Dropped!" );
      }
    });
  });
  </script>
</head>
<body>

<div id="draggable" class="ui-widget-content">
  <p>Drag me to my target</p>
</div>

<div id="droppable" class="ui-widget-header">
  <p>Drop here</p>
</div>


</body>
</html>
```

**Comment by selinaross** [comment]
After trying to work on a drop down menu, I realized draggable/droppable with jQuery UI is a more straight forward solution. I've been working on this and will commit my code soon. I'm interested in the group's feedback and am open to other solutions. 

@patrickmulcrone - I'm sorry if you've already created the UI buttons for the menu and delete options. We can still go this route if that's what the group prefers. 

@nw - I feel like I'm on a roll with drag/drop (dragging the "book" to the collection box to save it to the desired collection category), but if you have any suggestions/concerns, I'd love to hear them. I plan to use jQuery UI tooltip https://jqueryui.com/tooltip/ to make it clear to the user to drag/drop. We can also put instructions on the page – something like “drag books to save to library collection/shelf.”

**Comment by nw** [comment]
Fun stuff to play with. Glad your own a roll. Let me know if you have questions. More importantly code to review or help with.

**Comment by selinaross** [comment]
Thanks, Nate. Will do!

**Comment by patrickmulcrone** [comment]
Cool, I'm 100% on board!

**Comment by ysjoyce** [comment]
Do I incorporate the drag-drop code into my existing code?

**Comment by ysjoyce** [comment]
Let's clarify:
1.  Search screen, input subject.
2.  8 responses from search. Two rows of 4 books with thumbnail, Title and Author.
3. Choice time. Either drag-drop to one of the four categories, or eliminate (color or shade will change).
4. Click on one of the categories to see what has been stored. 
5. Storage format is the same as search result format, 4 x 2, with thumbnail, title, author and ID for future search. 
Question:  What does the book information look like after it has been stored or deleted?

**Comment by patrickmulcrone** [comment]
Yvonne, that's a really good question. I think that:
1. when it is stored we give it a border color with the collection color, but leave it in place visually, so that way it can be added to another collection if the the user wants.
2. deleting- because we can not replace it with the next result item which would be ideal (which I don't expect you to code, btw), we could create an click event that changes css to 
   display: none 
   so that the other tiles slide  over it into place. We can try this anyway.

**Comment by selinaross** [comment]
@ysjoyce - to answer your question about incorporating the drag-drop code into your existing code... I believe I just need the JSON object from you that is associated with each tile (search results) to store in the categories/collections (local storage). Then, we can merge my drag-drop (and local storage) code into yours. Since you have a lot more code, I'm thinking it will be easier this way. Does this seem right?

**Comment by selinaross** [comment]
I added a comment in Slack and am posting it here in case you all didn't see it there:

Hi everyone - Just so we don't duplicate efforts, I wanted to say that I'm working on changing the background-color of the tile to match the collection it's saved to (since it's part of the drop event). Let me know if this causes any problems for anyone and/or if you have any questions.

**Comment by selinaross** [comment]
Drag & drop is now functional on the search page - see pull request #34 "drag & drop capability."

**Comment by nw** [comment]
:100: :+1:  I saw! Looking good!

I think you and @patrickmulcrone are crushing it on the git workflow. Great job guys!

**Comment by selinaross** [comment]
@nw - Hey, thanks Nate!
