### ISSUE TITLE
Customize Bootstrap

### ISSUE THREAD

**Issue by patrickmulcrone** [WebDevBootcamp/archiVe#15]
Any issues customizing bootstrap to have 5 columns (or multiples of 5?)

**Comment by patrickmulcrone** [comment]
Note: Customize bootstrap columns http://getbootstrap.com/customize/

**Comment by nw** [comment]
Yeah you can build your own package. I would suggest either using a 10
column grid system or opting to stick with the original 12 and switching to
6 columns.

**Comment by selinaross** [comment]
Patrick completed.
