### ISSUE TITLE
Logo samples

### ISSUE THREAD

**Issue by patrickmulcrone** [WebDevBootcamp/archiVe#18]
Here are a few examples of what the logo could be based on your earlier discussions. I imagine we would display either of these while app initially loads, then simply display the book icon alone in a top corner while someone is searching/ using the app.

![01_welcomeloadingscreen](https://cloud.githubusercontent.com/assets/8552438/7595670/a4492f90-f8a5-11e4-9955-5a47d62a8498.jpg)

![01_welcomeloadingscreen_archivebigbook](https://cloud.githubusercontent.com/assets/8552438/7595675/ac8ea39c-f8a5-11e4-9278-ac7b4bcb0a16.jpg)

**Comment by ysjoyce** [comment]
They look great Patrick. 
I like the one with the bigger logo.
