### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by patrickmulcrone** [WebDevBootcamp/archiVe#19]
When designing for phone/tablet, the result space is too small to show all 10 results legibly. Instead, I propose we use a scroll bar and display 5 rows by 2 columns.

![02_phonesearchscreen](https://cloud.githubusercontent.com/assets/8552438/7599302/0d11b3a4-f8be-11e4-8afe-e006c7f297e8.jpg)

**Comment by patrickmulcrone** [comment]
Description Screen
![03_description](https://cloud.githubusercontent.com/assets/8552438/7615532/779b03fe-f95b-11e4-9331-d879920a7634.jpg)

**Comment by patrickmulcrone** [comment]
Favorites Screen
![04_favorites](https://cloud.githubusercontent.com/assets/8552438/7619890/f19e9a0e-f978-11e4-9dc5-11e95e21458e.jpg)

**Comment by selinaross** [comment]
Wow! Nice work, Patrick!
