### ISSUE TITLE
create description page

### ISSUE THREAD

**Issue by selinaross** [WebDevBootcamp/archiVe#22]
see wireframe for reference

**Comment by selinaross** [comment]
Modal using Bootstrap http://getbootstrap.com/javascript/

**Comment by selinaross** [comment]
Hey group - I don't think I'll get to this until tomorrow. So, if anyone wants to jump in and do it, that's fine by me. Otherwise, I'll work on it in class tomorrow night. I'll remove my name from this issue for now.

**Comment by ysjoyce** [comment]
We will not get to do a modal. We can instead, as we talked about, have a simple page with the existing image, title, author, and published date information, and add a div with additional information such as, description, retail price, available download, etc. This can be obtained by a future, separate download.

**Comment by selinaross** [comment]
This is a future enhancement.
