### ISSUE TITLE
research pinterest api

### ISSUE THREAD

**Issue by dlpeters** [WebDevBootcamp/archiVe#3]
determine if pinterest is of value to create media shelf

**Comment by selinaross** [comment]
I looked into this a little bit and realize it could be of use later on in the project, but probably will complicate things at this point.

**Comment by dlpeters** [comment]
I think we can use the google viewer for producing the pictures ... it also has all the buttons to click to open the book, search book contents, etc. 

I am working on a prototype (to be modified for our purposes). Maybe we can come up with a cool unique imaging display or Some other use to be added? 

The google ibook interface is pretty complete in the various parts (makes the bookshelf and all the capabilities we were talking about). Pretty amazing. Defineately couldn't compete with google! 

----- Original Message -----

**Comment by selinaross** [comment]
That's great, it sounds like the ibook API has all we need. Thanks for working on a prototype. I will look at the ibook API this afternoon and sketch out my thoughts on a db structure (to be modified with everyone's input).
