### ISSUE TITLE
Working code

### ISSUE THREAD

**Issue by ysjoyce** [WebDevBootcamp/archiVe#42]
I vote for leaving the code as is and try to get the storage pages to show. If Nate can help us to do that with the existing code, we will have a working application.

**Comment by nw** [comment]
I'll be there early. The code I posted works for storage. We can piece it in. Should be trivial.

**Comment by selinaross** [comment]
Hi - I actually incorporated Nate's code and got everything working. Then,
I tried to incorporate Patrick's latest changes to index.html and style.css
(manually) and broke it! I'm working on getting back to where I was to make
it functional, then come to class to get help with getting Patrick's style
changes merged.
